// The input state machine. Every case starts from a pinned state (fresh: AC, arc, sign off, wrap on).
const H = require('./h'); const { run, press, fresh, wrap, signView, dms, hms, S, check, summary } = H;
(async () => {
  const { browser, page, errs } = await H.open(); let v;
  const f = () => fresh(page, 'arc');
  await f(); v = await run(page, '=');                  check('= on the empty display', v.msg, 'Nothing to work out yet.');
  await f(); v = await run(page, '+ 5 =');              check('+ 5 = on the empty display', v.val, dms(S(5)));
  await f(); v = await run(page, 'n');                  check('± on the empty display starts a negative entry', v.val, '−0° 00′ 00″');
  await f(); v = await run(page, '0 = n');              check('0 = ± negates the committed 0', v.last, '−(0° 00′ 00″) = 0° 00′ 00″');
  v = await run(page, '5 =');                           check('  then 5 = is positive', v.val, dms(S(5)));
  await f(); v = await run(page, '5 + - * / + 3 =');    check('operator changes before typing', v.val, dms(S(8)));
  await f(); v = await run(page, '5 * + 3 =');          check('× changed to +', v.val, dms(S(8)));
  await f(); v = await run(page, '5 + * 2 =');          check('+ changed to ×', v.val, dms(S(10)));
  await f(); v = await run(page, '5 + 3 -');            check('operator after typing evaluates', v.pending, '8° 00′ 00″ −');
  await f(); v = await run(page, '5 + 3 C');            check('C clears the right value, keeps the operation', v.pending + '|' + v.val, '5° 00′ 00″ +|0° 00′ 00″');
  v = await run(page, '4 =');                           check('  then 4 =', v.val, dms(S(9)));
  await f(); v = await run(page, '5 + 3 C C');          check('C C clears all', v.pending + '|' + v.val, '|0° 00′ 00″');
  await f(); v = await run(page, '5 + M:time 3 =');     check('arc + time refused', v.msgBad, true);
  v = await run(page, 'M:arc 3 =');                     check('  tap ° and retype', v.val, dms(S(8)));
  await f(); v = await run(page, '5 + M:time 3 = @OE =');  check('  or recall a register', v.val, dms(S(28,26)));
  await f(); v = await run(page, '5 / 0 =');            check('÷ 0 refused, operation kept', v.msgBad + '|' + v.pending, 'true|5° 00′ 00″ ÷');
  v = await run(page, '2 =');                           check('  then 2 =', v.val, dms(S(2,30)));
  await f(); v = await run(page, '5 + 3 sin');          check('unary on the right operand', v.val + '|' + v.right, '0.0523359…|true');
  v = await run(page, '=');                             check('  = then refuses arc + number', v.msgBad, true);
  v = await run(page, 'dec =');                         check('  dec converts it, = adds', v.val, dms(S(5,3,8)));
  await f(); v = await run(page, '5 * 2 dec');          check('dec on the × operand refused', v.msgBad, true);
  await f(); v = await run(page, '5 * 2 = dec');        check('dec on a result is a view', v.val, '10°');
  await f(); v = await run(page, '5 / 1 u = =');        check('= on a computed number stays', v.val, '5');
  v = await run(page, 'dec');                           check('  dec converts', v.val, dms(S(5)));
  await f(); v = await run(page, '5 / 1 u = M:time dec'); check('ratio, tap h, dec → time', v.val, hms(S(5)));
  await f(); v = await run(page, 'dec 1.5 dec');        check('dec on a typed number converts', v.val, dms(S(1,30)));
  await f(); v = await run(page, '23 u 26 u 12 dec');   check('dec on a typed arc → view', v.val, '23.43666°');
  v = await run(page, '5 =');                           check('  a digit with dec on types a number; = converts', v.val, dms(S(5)));
  await f(); v = await run(page, 'M:time 15 u 55 / 24 u ='); check('÷ 24 h m s → ratio', v.val, '0.6631944…');
  await f(); v = await run(page, 'M:time 15 u 55 / 24 =');   check('÷ 24 → time', v.val, hms(S(0,39,48)));
  await f(); v = await run(page, 'M:time 15 u 55 / M:arc');  check('÷ then ° refused (time ÷ arc)', v.msgBad, true);
  await f(); v = await run(page, 'M:time 15 u 55 / 2.5 u');  check('÷ 2.5 then h m s refused', v.msgBad, true);
  await f(); v = await run(page, 'M:time 15 u 55 * 2 u');    check('× 2 h m s refused (ratio hint)', v.msgBad, true);
  await f(); v = await run(page, 'dec 2 * 3 u 30 =');        check('number × 3° 30′', v.val, dms(S(7)));
  await f(); v = await run(page, 'dec 2 / 3 u');             check('number ÷ ° refused', v.msgBad, true);
  await f(); v = await run(page, 'dec 2 + 3 u');             check('number + ° refused', v.msgBad, true);
  await f(); v = await run(page, '5 / 2 u 30 =');            check('5° ÷ 2° 30′ = 2', v.val, '2');
  await f(); v = await run(page, '5 / 361 u');               check('÷ 361 ° refused', v.msgBad, true);
  await f(); v = await run(page, 'M:time 5 / 25 u');         check('÷ 25 h m s refused', v.msgBad, true);
  await f(); v = await run(page, '5 / 0 u 60');              check('60 in the minutes refused', v.msgBad, true);
  await f(); await press(page, '23 u 26 u 54 >OE');
  v = await run(page, 'AC 5 + @OE =');                       check('recall into the right slot', v.val, dms(S(28,26,54)));
  await f(); v = await run(page, '5 + @OE 3 =');             check('typing after a recall replaces it', v.val, dms(S(8)));
  await f(); v = await run(page, '5 + 3 sto @x =');          check('store the typed right operand, = still works', v.regs.x.sec + '|' + v.val, S(3) + '|' + dms(S(8)));
  await f(); v = await run(page, '5 + sto @x');              check('sto in an empty right slot refused', v.msgBad, true);
  await f(); v = await run(page, '5 + 3 = = =');             check('repeated =', v.val, dms(S(8)));
  await f(); v = await run(page, '23 u 26 bs bs bs');        check('backspace across fields', v.val, '23° 00′ 00″');
  await f(); v = await run(page, 'n bs');                    check('backspace removes the minus', v.val, '0° 00′ 00″');
  await f(); v = await run(page, '5 + 3 = bs');              check('backspace on a result refused', v.msgBad, true);
  await f(); v = await run(page, '5 n');                     check('± mid-entry', v.val, '−5° 00′ 00″');
  v = await run(page, 'u 30 n =');                           check('  ± again', v.val, dms(S(5,30)));
  v = await run(page, 'n');                                  check('± on a value writes a line', v.last, '−(5° 30′ 00″) = −5° 30′ 00″');
  await f(); v = await run(page, '90 cos n');                check('± on a computed 0 stays a number', v.val + '|' + v.sval.k + '|' + v.last, '0|dec|−(0) = 0');
  v = await run(page, '/ 2 = atan');                         check('  ÷ 2 = tan⁻¹ → 0°', v.val, dms(0));
  await f(); v = await run(page, '3 - 5 =');                 check('3 − 5 wraps', v.val, dms(S(358)));
  await f(); v = await run(page, 'n 3 - 5 =');               check('−3 − 5 stays signed', v.val, '−' + dms(S(8)));
  await f(); v = await run(page, 'M:time n 3 + 2 =');        check('times always wrap', v.val, hms(S(23)));
  await f(); v = await run(page, 'n 200 p180');              check('−200° +180 stays signed', v.val, '−' + dms(S(20)));
  await f(); v = await run(page, '200 p180');                check('200° +180 wraps', v.val, dms(S(20)));
  await f(); v = await run(page, 'M:time n 1 x15');          check('−01:00 ×15', v.val, '−' + dms(S(15)));
  await f(); v = await run(page, 'M:time 24 x15');           check('24:00 ×15 = 360°', v.val, dms(S(360)));
  await f(); v = await run(page, '360 d15');                 check('360° ÷15 = 24:00', v.val, hms(S(24)));
  await f(); v = await run(page, '360 u 30');                check('360° 30′ refused', v.msgBad, true);
  await f(); v = await run(page, 'M:time 24 u 30');          check('24:30 refused', v.msgBad, true);
  await f(); v = await run(page, '340 u 10 + 31 u 50 =');    check('340° 10′ + 31° 50′ with the note', v.val + '|' + v.note, '12° 00′ 00″|372° 00′ 00″ → 12° 00′ 00″');
  await f(); v = await run(page, '23 u 26 M:time');          check('° → h mid-entry keeps the digits', v.val, '23:26:00');
  await f(); v = await run(page, '25 u 26 M:time');          check('25 → h refused', v.msgBad, true);
  await f(); v = await run(page, 'n 5 M:time M:arc =');      check('± 5, h, ° = keeps the minus', v.val, '−' + dms(S(5)));
  await f(); v = await run(page, 'dec n 5 M:time M:arc =');  check('dec ± 5, h, ° = keeps the minus', v.val, '−' + dms(S(5)));
  await f(); await press(page, '5 + 3'); await wrap(page, false); v = await run(page, '=');  check('wrap toggled mid-entry', v.val + '|' + v.wrap, '8° 00′ 00″|false'); await wrap(page, true);
  await f(); await press(page, '5 + 3'); await page.evaluate(() => window.takht.applyLang('ja')); v = await run(page, '='); await page.evaluate(() => window.takht.applyLang('en')); check('language switched mid-entry', v.val, dms(S(8)));
  await f(); await page.evaluate(() => window.takht.applyLang('fr')); v = await run(page, '5 / 3 u ='); await page.evaluate(() => window.takht.applyLang('en')); check('French ratio uses a comma', v.val, '1,6666666…');
  // sign-form entry
  await f(); await signView(page, true);
  v = await run(page, '25 u 21 u 41 u u u u u u u u u =');   check('sign entry ♐ = 265° 21′ 41″', v.val + '|' + v.last, '25° 21′ 41″ ♐|25° 21′ 41″ ♐ = 265° 21′ 41″');
  v = await run(page, 'AC 25 u 21 u 41 =');                  check('= without a sign refused', v.msgBad, true);
  v = await run(page, 'AC 30');                              check('30 in a sign refused', v.msgBad, true);
  v = await run(page, 'AC 5 n');                             check('± in sign entry refused', v.msgBad, true);
  v = await run(page, 'AC n');                               check('± on the empty sign entry refused', v.msgBad, true);
  v = await run(page, 'AC 0 u u u = n');                     check('± on a committed 0 ♈ negates, no new entry', v.last + '|' + (v.entry == null), '−(0° 00′ 00″ ♈ (0° 00′ 00″)) = 0° 00′ 00″|true');
  v = await run(page, 'AC 25 u 21 u 41 sign');               check('sign off before choosing keeps the digits', v.val + '|' + v.view.sign, '25° 21′ 41″|false'); await signView(page, true);
  v = await run(page, 'AC M:time n 5 M:arc');                check('sign on: h ± 5 ° is an absolute negative entry', v.val + '|' + JSON.stringify(v.entry && [v.entry.sign, v.entry.neg]), '−5° 00′ 00″|[false,true]');
  v = await run(page, '=');                                  check('  = keeps the minus (sign view shows 25° ♓)', v.sval.sec + '|' + v.val, '-18000|25° 00′ 00″ ♓');
  v = await run(page, 'AC 5 u u u u M:time M:arc =');        check('a chosen sign taken through h and back must be chosen again', v.msgBad, true);
  await signView(page, false);
  await f(); v = await run(page, 'M:time 5 sign');           check('sign in time refused', v.msgBad, true);
  await f(); v = await run(page, '5 / 1 u = sign');         check('sign on a computed number refused', v.msgBad, true);
  // keyboard
  await f(); await page.keyboard.type("23'26\"12+48'13\"56"); await page.keyboard.press('Enter'); v = await H.view(page); check('keyboard: 23°26′12″ + 48°13′56″ Enter', v.val, dms(S(71,40,8)));
  await page.keyboard.press('m'); await page.keyboard.type('15 55'); await page.keyboard.press('t'); v = await H.view(page); check('keyboard: m, Space, t', v.val, dms(S(238,45)));
  await page.keyboard.press('T'); await page.keyboard.press('d'); v = await H.view(page); check('keyboard: T, d', v.val, '15.91666 h');
  await page.keyboard.press('d'); await page.keyboard.press('n'); v = await H.view(page); check('keyboard: n', v.val, '−' + hms(S(15,55)));
  await page.keyboard.press('Escape'); await page.keyboard.press('Escape'); await page.keyboard.press('?'); check('keyboard: ? opens Help', await page.evaluate(() => document.querySelector('#help').classList.contains('open')), true); await page.keyboard.press('Escape');
  // mixed kinds: a decimal on the right can be turned by dec; one already on the left of + cannot, so the message says start again
  await fresh(page, 'time'); await press(page, 'AC M:time 1 u >LST');
  v = await run(page, 'AC dec .5 + @LST =');            check('decimal + time, decimal on the left: start again', v.msg, 'A decimal and h m s cannot be added. Press C twice, type the decimal, press dec, then +.');
  v = await run(page, 'C C dec .5 dec + @LST =');        check('  following it gives 01:30:00', v.val, hms(S(1,30)));
  v = await run(page, 'AC @LST + dec .5 =');             check('time + decimal, decimal on the right: press dec on it', v.msg, 'A decimal and h m s cannot be added. Press dec on the decimal to turn it into h m s.');
  v = await run(page, 'dec =');                          check('  following it gives 01:30:00', v.val, hms(S(1,30)));
  check('no page errors', errs.join('|'), ''); summary(); await browser.close();
})();
